/**
 * Pure-TypeScript Keccak-256 implementation (no external dependencies).
 *
 * Implements the original Keccak specification (not NIST SHA-3).
 * Ethereum uses Keccak-256 with 0x01 domain padding.
 *
 * Reference: https://keccak.team/keccak_specs_summary.html
 */

const MASK64 = BigInt("0xFFFFFFFFFFFFFFFF");

/** Rotate a 64-bit lane left by n bits. */
function rot64(x: bigint, n: number): bigint {
  if (n === 0) return x & MASK64;
  return (((x << BigInt(n)) | (x >> BigInt(64 - n))) & MASK64);
}

/**
 * Keccak-f[1600] round constants (24 rounds).
 * Generated by the LFSR described in the Keccak reference.
 */
const RC: readonly bigint[] = [
  0x0000000000000001n, 0x0000000000008082n, 0x800000000000808an, 0x8000000080008000n,
  0x000000000000808bn, 0x0000000080000001n, 0x8000000080008081n, 0x8000000000008009n,
  0x000000000000008an, 0x0000000000000088n, 0x0000000080008009n, 0x000000008000000an,
  0x000000008000808bn, 0x800000000000008bn, 0x8000000000008089n, 0x8000000000008003n,
  0x8000000000008002n, 0x8000000000000080n, 0x000000000000800an, 0x800000008000000an,
  0x8000000080008081n, 0x8000000000008080n, 0x0000000080000001n, 0x8000000080008008n,
] as const;

/**
 * Rho rotation offsets indexed by x + 5*y (lane index).
 * Derived from the Keccak traversal algorithm: offset for lane at (x, y)
 * = (t+1)*(t+2)/2 mod 64, where t is when that lane enters the rotation chain.
 *
 * Verified against the official Keccak spec rotation table:
 *   x/y  0   1   2   3   4
 *    0    0  36   3  41  18
 *    1    1  44  10  45   2
 *    2   62   6  43  15  61
 *    3   28  55  25  21  56
 *    4   27  20  39   8  14
 */
const RHO: readonly number[] = [
  // y=0: x=0..4
   0,  1, 62, 28, 27,
  // y=1: x=0..4
  36, 44,  6, 55, 20,
  // y=2: x=0..4
   3, 10, 43, 25, 39,
  // y=3: x=0..4
  41, 45, 15, 21,  8,
  // y=4: x=0..4
  18,  2, 61, 56, 14,
] as const;

/** Keccak-f[1600] permutation — applies 24 rounds to the 25-lane state in-place. */
function keccakF(state: bigint[]): void {
  const C = new Array<bigint>(5);
  const D = new Array<bigint>(5);
  const B = new Array<bigint>(25);

  for (let round = 0; round < 24; round++) {
    // θ (Theta): XOR column parities
    for (let x = 0; x < 5; x++) {
      C[x] = state[x]! ^ state[x + 5]! ^ state[x + 10]! ^ state[x + 15]! ^ state[x + 20]!;
    }
    for (let x = 0; x < 5; x++) {
      D[x] = C[(x + 4) % 5]! ^ rot64(C[(x + 1) % 5]!, 1);
    }
    for (let i = 0; i < 25; i++) {
      state[i] = state[i]! ^ D[i % 5]!;
    }

    // ρ (Rho) + π (Pi): rotate and permute lanes
    for (let x = 0; x < 5; x++) {
      for (let y = 0; y < 5; y++) {
        const src = x + 5 * y;
        const newX = y;
        const newY = (2 * x + 3 * y) % 5;
        B[newX + 5 * newY] = rot64(state[src]!, RHO[src]!);
      }
    }

    // χ (Chi): non-linear mix
    for (let y = 0; y < 5; y++) {
      for (let x = 0; x < 5; x++) {
        const i = x + 5 * y;
        state[i] = (B[i]! ^ ((~B[((x + 1) % 5) + 5 * y]!) & B[((x + 2) % 5) + 5 * y]!)) & MASK64;
      }
    }

    // ι (Iota): XOR round constant into lane (0,0)
    state[0] = (state[0]! ^ RC[round]!) & MASK64;
  }
}

/**
 * Compute Keccak-256 of the given byte array.
 *
 * Uses rate = 1088 bits (136 bytes) and capacity = 512 bits.
 * Padding: 0x01 byte, zeros, 0x80 at end of block (original Keccak, not NIST SHA-3).
 */
export function keccak256(data: Uint8Array): Uint8Array {
  const RATE = 136; // 1088 bits / 8 = 136 bytes

  // Pad input: append 0x01, zero-fill, set top bit of last byte
  const totalLen = data.length + (RATE - (data.length % RATE));
  const padded = new Uint8Array(totalLen);
  padded.set(data);
  padded[data.length] = 0x01;
  // Safe: totalLen is always >= 1 (RATE = 136 > 0)
  const lastIdx = totalLen - 1;
  padded[lastIdx] = (padded[lastIdx] ?? 0) | 0x80;

  // Initialize 25-lane (1600-bit) state
  const state: bigint[] = new Array(25).fill(0n);

  // Absorb
  const lanesPerBlock = RATE / 8; // 17 lanes
  for (let blockStart = 0; blockStart < totalLen; blockStart += RATE) {
    for (let lane = 0; lane < lanesPerBlock; lane++) {
      let word = 0n;
      const base = blockStart + lane * 8;
      for (let byte = 0; byte < 8; byte++) {
        const b = padded[base + byte] ?? 0;
        word |= BigInt(b) << BigInt(8 * byte);
      }
      state[lane] = state[lane]! ^ word;
    }
    keccakF(state);
  }

  // Squeeze: extract first 32 bytes (256 bits)
  const output = new Uint8Array(32);
  for (let i = 0; i < 32; i++) {
    output[i] = Number((state[Math.floor(i / 8)]! >> BigInt(8 * (i % 8))) & 0xffn);
  }
  return output;
}
